MATRIX AND VECTOR

In [1]:
import numpy as np 

In [2]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
v = np.array([[1],[2],[3]])

In [5]:
v

array([[1],
       [2],
       [3]])

In [6]:
M.dtype

dtype('int32')

In [7]:
M.shape

(3, 3)

In [8]:
v.dtype

dtype('int32')

In [9]:
v.shape

(3, 1)

In [10]:
v_single_dim = np.array([1,2,3])

In [11]:
v_single_dim

array([1, 2, 3])

In [14]:
v_single_dim.shape

(3,)

In [15]:
print(v + v)

[[2]
 [4]
 [6]]


In [16]:
print(3 * v)

[[3]
 [6]
 [9]]


In [19]:
a = np.zeros((2,2)) # Create an array of all zeros
print(a)            # Prints"[[0. 0.]
                    #         [0. 0.]]"

b = np.ones((1,2))  # Create an array of all ones
print(b)            # Prints "[[1. 1.]]"

c = np.full((2,2), 7) # Create a constant array 
print(c)              # Prints "[[7. 7.]
                      #          [7. 7.]]"

d = np.eye(2)       # Create a 2x3 identity matrix
print(d)            # Prints "[[1. 0.]
                    #          [0. 1.]]"

e = np.random.random((2,2)) # Create an array filled with random values
                            # Might print "[[ 0.91940167  0.08143941]
                            #               [ 0.68744134  0.87236687]]"
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.44310508 0.18933884]
 [0.694976   0.85770847]]


In [20]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
v3 = np.array([7,8,9])
M = np.vstack([v1, v2, v3])
print(M)

# There is also a way to do this horizontally => hstack

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [27]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr[0:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
arr[2,1:]

array([11, 12, 13, 14])

In [32]:
arr[:2,2:4]

array([[2, 3],
       [7, 8]])

In [33]:
arr[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [34]:
arr[::2,::3]

array([[ 0,  3],
       [10, 13]])

Matrix Reshape

In [36]:
import numpy as np
m = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print(m)
rm = m.reshape((5,3))
print(rm)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
b = np.array([[1,0],[2,5],[3,1]])
c = np.array([[4,0.5],[2,5],[0,1]])
print(b)
print(c)
d = b+c
print(d)

[[1 0]
 [2 5]
 [3 1]]
[[4.  0.5]
 [2.  5. ]
 [0.  1. ]]
[[ 5.   0.5]
 [ 4.  10. ]
 [ 3.   2. ]]


In [38]:
a = np.array([[1,0],[2,5],[3,1]])
add_a_3=a+3
print(add_a_3)
mul_a_3=a*3
print(mul_a_3)

[[4 3]
 [5 8]
 [6 4]]
[[ 3  0]
 [ 6 15]
 [ 9  3]]


In [39]:
e = np.array([[1],[4],[2]])
f = np.array([[0],[0],[5]])
g = np.array([[3],[0],[2]])

h=3 * e + f - g /3
print(e)
print(f)
print(g)
print(h)

[[1]
 [4]
 [2]]
[[0]
 [0]
 [5]]
[[3]
 [0]
 [2]]
[[ 2.        ]
 [12.        ]
 [10.33333333]]


In [40]:
h = np.array([[1,3],[4,0],[2,1]]) # 3x2
i = np.array([[1],[5]]) # 2x1

dot_h_i = np.dot(h,i)
print(h)
print(i)
print(dot_h_i)

[[1 3]
 [4 0]
 [2 1]]
[[1]
 [5]]
[[16]
 [ 4]
 [ 7]]


In [45]:
l = np.array([[1,3,2],[4,0,1]])
m = np.array([[1,3],[0,1],[5,2]])
dot_l_m = np.dot(l,m)
print(l)
print(m)
print(dot_l_m)

[[1 3 2]
 [4 0 1]]
[[1 3]
 [0 1]
 [5 2]]
[[11 10]
 [ 9 14]]


In [46]:
A = np.array([[4,2,1],[4,8,3],[1,1,0]])
I = np.identity(3, dtype=int)
dot_A_I = np.dot(A,I)
dot_I_A = np.dot(I,A)
print(A)
print(I)
print(dot_A_I)
print(dot_I_A)

[[4 2 1]
 [4 8 3]
 [1 1 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[4 2 1]
 [4 8 3]
 [1 1 0]]
[[4 2 1]
 [4 8 3]
 [1 1 0]]


In [51]:
A = np.array([[4,2,1],[4,8,3],[1,1,0]])
inv_A=np.linalg.inv(A)
print(A)
print(inv_A)

[[4 2 1]
 [4 8 3]
 [1 1 0]]
[[ 0.3 -0.1  0.2]
 [-0.3  0.1  0.8]
 [ 0.4  0.2 -2.4]]


In [55]:
A = np.array([[1,2,0],[3,5,9]])
A_T=A.T
print(A)
print(A_T)

[[1 2 0]
 [3 5 9]]
[[1 3]
 [2 5]
 [0 9]]


In [56]:
A = np.array(([1,2,7],[3,5,9]))
log_A=np.log(A)
pow_A=np.power(A,2)
print(A)
print(log_A)
print(pow_A)

[[1 2 7]
 [3 5 9]]
[[0.         0.69314718 1.94591015]
 [1.09861229 1.60943791 2.19722458]]
[[ 1  4 49]
 [ 9 25 81]]
